file_uploader/file_uploader/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pic_upload.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_uploader/pic_upload/urls.py
from django.urls import re_path, include
from .views import PicDetail, PicList, PicUpload
from .views import PictureUpload, PictureList, PictureDetail

app_name = 'pic_upload'

urlpatterns = [
    re_path(r'^$', PictureList.as_view(), name='pic_list'),
    re_path(r'^pic/upload/$', PictureUpload.as_view(), name='pic_upload'),
    re_path(r'^pic/(?P<id>\d+)/$', PictureDetail.as_view(), name='pic_detail'),
]

file_uploader/pic_upload/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.
class Picture(models.Model):
    title = models.CharField(max_length=100, blank=True, default='Unknown')
    #image = models.ImageField(upload_to=settings.IMAGE_DIR)
    image_url = models.TextField(blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pic_upload:pic_detail', args=[str(self.id)])

    class Meta:
        db_table = 'picture'
        ordering =  ['-date']

file_uploader/pic_upload/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from django.views import View
from django.conf import settings
from django.utils.crypto import get_random_string

from .models import Picture
from .form import ImageUploadForm

import os
import hashlib

def generate_image_name(title):
    salt = get_random_string(10)
    data = bytes(title + salt, 'utf-8')
    
    return str(hashlib.sha256(data).hexdigest())


class PictureUpload(View):
    def get(self, request):
        form = ImageUploadForm()

        return render(request, 'picture_upload.html', {'form' : form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)

        if form.is_valid():
            title = form.cleaned_data['title']
            img = form.cleaned_data['image']

            suffix = os.path.splitext(img.name)[-1].lower()
            name = generate_image_name(title) + suffix
            with open(os.path.join(settings.IMAGE_UPLOAD_DIR, name), 'wb') as f:
                for chunk in img:
                    f.write(chunk)

            p = Picture.objects.create(title=title, image_url=f"{settings.IMAGE_URL_PREFIX}/{name}")
            
            return redirect(reverse('pic_upload:pic_detail', args=[str(p.id)]))
        else:
            return redirect(reverse('pic_upload:pic_upload'))

class PictureDetail(View):
    def get(self, request, id):
        picture = Picture.objects.get(id=id)

        return render(request, 'picture_detail.html', {'picture' : picture})

class PictureList(View):
    def get(self, request):
        picture_list = Picture.objects.all()

        return render(request, 'picture_list.html', {'picture_list' : picture_list})

# Create your views here.
class PicList(ListView):
    queryset = Picture.objects.all().order_by('-date')

    context_object_name = 'latest_picture_list'

    template_name = "picture_list.html"

class PicDetail(DetailView):
    model = Picture

    template_name = "picture_detail.html"

class PicUpload(CreateView):
    model = Picture

    fields = ['title', 'image']

    template_name = "picture_upload.html"

file_uploader/pic_upload/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

file_uploader/pic_upload/templates/picture_detail.html
{% extends 'base.html' %}

{% block content %}
<h3>{{ picture.title }}</h3>

{% if picture %}
  <p><img src="{{ picture.image_url }}"/></p>
{% endif %}

<p>Upload Date: {{ picture.date | date:"Y-m-j" }} </p>
<p><a href="{% url 'pic_upload:pic_list' %}">Show All Pictures</a> |
    <a href="{% url 'pic_upload:pic_upload' %}">Upload New Picture</a></p>
{% endblock %}

file_uploader/pic_upload/templates/picture_list.html
{% extends 'base.html' %}

{% block content %}
<h3>Picture List</h3>
<ul>
{% if picture_list %}
    {% for picture in picture_list %}
    <li><a href="{% url 'pic_upload:pic_detail' picture.id %}">{{ picture.title }}</a>
        - {{ picture.date| date:"Y-m-j" }}</li>
    {% endfor %}
{% else %}
    <li>No Picture</li>
{% endif %}
</ul>
<p><a href="{% url 'pic_upload:pic_upload' %}">Upload Picture</a></p>
{% endblock %}

file_uploader/pic_upload/templates/picture_upload.html
{% extends 'base.html' %}

{% block content %}
<h3>Upload Picture</h3>
{% if form.errors %}
<p>Something Wrong</p>
{% endif %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
<p><a href="{% url 'pic_upload:pic_list' %}">Back to home</a></p>
{% endblock %}