TodoService/TodoService/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include(('home.urls', 'home'), namespace='home')),
    path('register/', include(('registration.urls', 'registration'), namespace='register')),
    path('todo/', include(('todo.urls', 'todo'), namespace='todo')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

TodoService/home/urls.py
from django.urls import path, re_path
from .views import HomeView

app_name = 'home'

urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
]

TodoService/registration/urls.py
from django.urls import re_path
from .views import UserRegistration, UserLoginView, UserLogoutView

app_name = 'registration'

urlpatterns = [
    re_path(r'^$', UserRegistration.as_view(), name='register'),
    re_path(r'^login/$', UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', UserLogoutView.as_view(), name='logout'),
]

TodoService/todo/urls.py
from django.urls import path, re_path
from .views import TodoView, delete_todo_item, cross_off_item

app_name = 'todo'

urlpatterns = [
    re_path(r'^$', TodoView.as_view(), name='list'),
    re_path(r'^delete/(?P<todo_id>[0-9]+)/$', delete_todo_item, name='delete'),
    re_path(r'^cut/(?P<todo_id>[0-9]+)/$', cross_off_item, name='cut'),
]

TodoService/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class TodoItem(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    finish_time = models.DateTimeField(null=True)
    is_cross_off = models.BooleanField(default=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']
        db_table = 'todo_item'

TodoService/home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
class HomeView(View):
    def get(self, request):
        return render(request, 'home.html')

TodoService/todo/views.py
from django.shortcuts import render, reverse, redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.conf import settings
from django.utils import timezone

from .models import TodoItem

@login_required
def delete_todo_item(request, todo_id):
    try:
        item = TodoItem.objects.get(id=todo_id, user=request.user)
        item.delete()
    except TodoItem.DoesNotExist:
        pass

    return redirect(reverse('todo:list'))

@login_required
def cross_off_item(request, todo_id):
    try:
        item = TodoItem.objects.select_for_update().get(id=todo_id, user=request.user)
        with transaction.atomic():
            item.is_cross_off = True
            item.finish_time = timezone.now()
            item.save(update_fields=['is_cross_off', 'finish_time'])
    except TodoItem.DoesNotExist:
        pass

    return redirect(reverse('todo:list'))

# Create your views here.
class TodoView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kargs):
        return super(TodoView, self).dispatch(request, *args, **kargs)

    def get(self, request):
        session = request.session

        todo_items = session.get(settings.USER_TODO_SESSION_ID, None)
        if todo_items is None:
            todo_items = TodoItem.objects.filter(user=request.user).order_by('-create_time')

        return render(request, 'todo.html', {'todo_items' : todo_items})

    def post(self, request):
        title = request.POST.get('title', "Unknown")
        content = request.POST.get('content', '')
        user = request.user

        p = TodoItem.objects.create(title=title, content=content, user=user)

        session = request.session
        todo_items = session.get(settings.USER_TODO_SESSION_ID, None)
        if todo_items:
            todo_items.append(p)
            session.modified = True

        return redirect(reverse('todo:list'))

TodoService/home/templates/home.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

{% block jumbotron %}
        <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
            <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">World</strong>
                <h3 class="mb-0">Featured post</h3>
                <div class="mb-1 text-muted">Nov 12</div>
                <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
            </div>
            {% if user.is_authenticated %}
            <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">Design</strong>
                <h3 class="mb-0">Post title</h3>
                <div class="mb-1 text-muted">Nov 11</div>
                <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
            </div>
            {% endif %}
        </div>
        </div>

        <footer class="blog-footer">
        <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        <p>
            <a href="#">Back to top</a>
        </p>
        </footer>
{% endblock %}

TodoService/templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Blog Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col text-center">
                    <a class="blog-header-logo text-dark" href="#">Todo Service</a>
                </div>
            </div>
        </header>

    {% include 'navbar.html' %}
    {% block jumbotron %}{% endblock %}
    {% block content %}{% endblock %}
    </div>
        <script src="{% static 'javascript/jquery-3.5.1.slim.min.js' %}" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/popper.min.js' %}" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/bootstrap.min.js' %}" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

TodoService/templates/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'todo:list' %}">My Todo</a>
        </li>
      {% else %}
        <li class="nav-item disabled">
          <a class="nav-link" href="{% url 'todo:list' %}">My Todo</a>
        </li>
      {% endif %}

      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav my-2 my-sm-0">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="">Profile</a>
                          <a class="dropdown-item" href="">Something here</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'register:logout' %}">Sign out</a>
                    </div>
            </li>
        {% else %}
            <li class="nav-item my-2 my-sm-0">
              <a class="nav-link active" href="{% url 'register:login' %}">Sign in</a>
            </li>
            <form action="{% url 'register:register' %}" method="get">
              <button type="submit" class="btn btn-outline-success">Sign up</button>
            </form>
        {% endif %}
      </ul>
    </div>
  </nav>

TodoService/todo/templates/todo.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'todo:list' %}" method="POST" class="form-inline">
      <div class="row mt-4">
          <div class="col-md-12">
              <h2>Add Todo Item</h2>
                  {% csrf_token %}

                  <input name="title" type="text" class="form-control mb-2 mr-md-4" id="inlineFormInputName2" placeholder="type here...">
                  <button type="submit" class="btn btn-primary mb-2">Submit</button>
          </div>
          <div class="col-lg-12">
                <textarea class="form-control" name="content" rows="4" cols="40" placeholder="describe here..."></textarea>
          </div>
      </div>
    </form>
    <div class="row mt-5">
        {% for item in todo_items %}
          <div class="col-md-6">
                    <div class="card">
                      <div class="card-body">
                        <h5 class="card-title">
                          {% if item.is_cross_off %}
                            <s>
                              {{ item.title }}
                            </s>
                            <div class=float-right>
                              {{ item.finish_time }}
                            </div>
                          {% else %}
                            {{ item.title }}
                          {% endif %}
                        </h5>
                          <div class="float-right">
                              <form action="cut/{{item.id}}/" method="post">
                                  <button  
                                  type="submit" class="btn btn-success mb-3">Cross off</button>
                                  {% csrf_token %}
                              </form>
                              <form action="delete/{{item.id}}/" method="post">
                                  <button  
                                  type="submit" class="btn btn-danger mb-3">Delete</button>
                                  {% csrf_token %}
                              </form>
                          </div>
                          <p class="card-text">
                            {{item.content|linebreaks}}
                          </p>
                      </div>
                    </div>
          </div>
        {% endfor %}

    </div>
{% endblock %}