ptt_blog/crawler/urls.py
from django.urls import re_path
from .views import TaskBoard, TaskSubmit

app_name = 'crawler'

urlpatterns = [
    re_path(r'^status/$', TaskBoard.as_view(), name='status'),
    re_path(r'^submit/$', TaskSubmit.as_view(), name='submit'),
]

ptt_blog/home/urls.py
from django.urls import path, re_path
from .views import Home

app_name = 'home'

urlpatterns = [
    re_path(r'^$', Home.as_view(), name='home'),
]

ptt_blog/ptt_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('crawler/', include(('crawler.urls', 'crawler'), namespace='crawler')),
]

ptt_blog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordered = ['-date', ]


class Push(models.Model):
    pusher = models.CharField(max_length=50)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class PostImage(models.Model):
    url = models.TextField(null=False)
    post = models.ManyToManyField(Post)

ptt_blog/crawler/models.py
from django.db import models

from enum import IntEnum

class TaskStatus(IntEnum):
    QUEUING = 0
    RUNNING = 1
    FINISH = 2
    ERROR = 3


TASK_STATUS_CHOICES = (
    (TaskStatus.QUEUING, 'In Queue'),
    (TaskStatus.RUNNING, 'Running'),
    (TaskStatus.FINISH, 'Finished'),
    (TaskStatus.ERROR, 'Error')
)

# Create your models here.
class CrawlTask(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    submit_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=TASK_STATUS_CHOICES, default=0)

    class Meta:
        ordering = ['-update_time', '-submit_time']

ptt_blog/crawler/forms.py
from django import forms
from .PttSpider.ptt_spider import PttUrl

class TaskForm(forms.Form):
    url = forms.CharField(max_length=100)

    def clean_url(self):
        url = self.cleaned_data.get('url')

        if not PttUrl.verify_url(url):
            raise forms.ValidationError('Url is not valid')

        return url

ptt_blog/blog/views.py
from django.shortcuts import render

# Create your views here.

ptt_blog/crawler/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View

from .models import CrawlTask
from .forms import TaskForm

from .tasks import create_crawl_task, crawler_init
from .tasks import m

# Create your views here.
class TaskBoard(View):
    def get(self, request):
        if m is None:
            crawler_init()

        # pagination
        task_list = CrawlTask.objects.all()
        return render(request, 'crawler_status.html', {'task_list' : task_list })

class TaskSubmit(View):
    def get(self, request, form=None):
        return render(request, 'crawler_submit.html')

    def post(self, request):
        form = TaskForm(request.POST)

        if form.is_valid():
            success = create_crawl_task(form.cleaned_data['url'])
            return redirect(reverse('crawler:status'))
        else:
            return render(request, 'crawler_submit.html', {'form':form})

ptt_blog/home/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class Home(View):
    def get(self, request):
        return render(request, 'home.html')

ptt_blog/home/templates/home.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

{% block jumbotron %}
        <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">
                Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.
            </p>
            </div>
        </div>
{% endblock %}

ptt_blog/templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>PTT Blog Tutorial</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col text-center">
                    <a class="blog-header-logo text-dark" href="#">Ptt Board</a>
                </div>
            </div>
        </header>

    {% include 'navbar.html' %}
    {% block jumbotron %}{% endblock %}
    {% block content %}{% endblock %}
    </div>
        <script src="{% static 'javascript/jquery-3.5.1.slim.min.js' %}" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/popper.min.js' %}" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/bootstrap.min.js' %}" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        
    </body>
</html>

ptt_blog/templates/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Crawler
            </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'crawler:status' %}">Status</a>
                      <a class="dropdown-item" href="{% url 'crawler:submit' %}">Add task</a>
                </div>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav my-2 my-sm-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dromdowns
                </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="">Profile</a>
                          <a class="dropdown-item" href="">Something here</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'home:home' %}">Sign out</a>
                    </div>
            </li>
      </ul>
    </div>
  </nav>