registraion_and_login/home/urls.py
from django.urls import re_path
from .views import Home

app_name = 'home'

urlpatterns = [
    re_path(r'^$', Home.as_view(), name='home'),
]

registraion_and_login/registraion_and_login/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    re_path('^$', include(('home.urls', 'home'), namespace='home')),
    path('register/', include(('registration.urls', 'registration'), namespace='register')),
]

registraion_and_login/registration/urls.py
from django.urls import re_path
from .views import UserRegistration, UserLoginView, UserLogoutView

app_name = 'registration'

urlpatterns = [
    re_path(r'^$', UserRegistration.as_view(), name='user'),
    re_path(r'^login/$', UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', UserLogoutView.as_view(), name='logout'),
]

registraion_and_login/home/views.py
from django.shortcuts import render, redirect
from django.views import View

# Create your views here.
class Home(View):
    def get(self, request):
        return render(request, 'home.html')

registraion_and_login/home/templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Blog Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col text-center">
                    <a class="blog-header-logo text-dark" href="#">N3kofi5t's Blog</a>
                </div>
            </div>
        </header>

    {% include 'navbar.html' %}
    {% block jumbotron %}{% endblock %}
    {% block content %}{% endblock %}
    </div>
        <script src="{% static 'javascript/jquery-3.5.1.slim.min.js' %}" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/popper.min.js' %}" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="{% static 'javascript/bootstrap.min.js' %}" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

registraion_and_login/home/templates/navbar.html
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'register:logout' %}">Sign out</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'register:user' %}">Sign up</a>
                    <a class="dropdown-item" href="{% url 'register:login' %}">Sign in</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
      </ul>
    </div>
  </nav>